export const DOMAIN = "https://dev-esexpressv1.kirana11.com/";
export const PRODUCT_DEALS_FETCH = DOMAIN + "deals_product?type=Shocking Deals";
export const PRODUCT_WITH_CATEGORIES_FETCH = DOMAIN + "category_menu";
export const PRODUCT_BY_PID_FETCH = DOMAIN + "variation?pid=";
export const PRODUCT_BY_NID_FETCH = DOMAIN + "product?nid=";
export const LISTING_BY_ID_CATEGORY = DOMAIN ;
export const HOMEPAGE_CAT_DEALS = DOMAIN +'category_deals_titles';
export const HOMEPAGE_CAT_DEALS_PRODUCTS = DOMAIN +'category_deals_products?cat_name=';
export const HOMEPAGE_BANNERS = DOMAIN+'banners?type=home_page_top_banners';
export const HOMEPAGE_EXCITING_DEALS_BANNER = DOMAIN +'banners?type=exciting_deals_banners';
export const HOMEPAGE_EXCITING_CAT_BANNERS = DOMAIN +"banners?type=category_deals_banners";
